### ISSUE TITLE
Erroneous label offset for Y axis.

### ISSUE THREAD

**Issue by laurimann** [xuanluo/flot-axislabels#6]
Error at line 100: y = plot.getPlotOffset().top + plot.height()/2 - width/2;
Fix for line 100: y = plot.getPlotOffset().top + plot.height()/2 + width/2;

**Comment by markrcote** [comment]
laurimann: If you are interested, I have fixed this bug and added more functionality to my fork: https://github.com/markrcote/flot-axislabels

**Comment by laurimann** [comment]
Thank you.

I have made some modifications myself too and on request i could share the code here somewhere. I see you made a fork of this project.

**Comment by markrcote** [comment]
Sure, if there are features I don't have in my fork, feel free to do a push request or just send me a patch/some code.
